name: scaffold_elements
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
#  flutter_speed_dial: ^6.0.0
#  flip_box_bar_plus: ^1.0.0
#  fancy_bottom_navigation: ^0.3.2
#  curved_navigation_bar: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/


#  fonts:
#    - family: Schyler
#      fonts:
#         - asset: fonts/Schyler-Regular.ttf

